# TD : Maîtriser les attributs Numpy
L'objectif de ce notebook est de manipuler les attributs fondamentaux des arrays Numpy pour comprendre la estion de l'espace, de la mémoire et des mécanisme de vue.

In [1]:
# Préparation
import numpy as np
import sys

print(f"Version de Numpy : {np.__version__}")

Version de Numpy : 2.4.3


## Exercice 1 : L'espace et les dimensions (`shape`, `ndim`, `size`)
Nous allons simuler les données de ventes de 3 magasins sur 4 jours.

**Mission :**
1. Crée le tableau.
2. Affiche le nombre de dimensions, la forme exacte du tableau, et le nombre total d'éléments.
3. Essaie d'ajouter un bonus de ventes (un tableau de 4 éléments) et observe ce qui se passe.

In [6]:
# 1. Création du tableau de ventes (3 magasins, 4 jours)
ventes = np.array([
    [120, 130, 110, 150],  # Magasin A
    [90, 85, 100, 110],    # Magasin B
    [200, 210, 195, 220]   # Magasin C
])

# 2. Inspection des attributs
print(f"Dimension (ndim) : {ventes.ndim}D")
line, column = ventes.shape
print(f"Forme (shape) : {ventes.shape}, ({line} lignes, {column} colonnes)")
print(f"Total des éléments (size) : {ventes.size}")

# 3. Le piège du broadcasting
bonus = np.array([10, 20, 15, 30])

# Essaye d'exécuter la ligne suivante.
# Si elle fonctionne, demande-toi pourquoi les dimensions (3,4) et (4,) sont compatibles !
ventes_avec_bonus = ventes + bonus
print("\n ventes avec bonus : \n", ventes_avec_bonus)

Dimension (ndim) : 2D
Forme (shape) : (3, 4), (3 lignes, 4 colonnes)
Total des éléments (size) : 12

 ventes avec bonus : 
 [[130 150 125 180]
 [100 105 115 140]
 [210 230 210 250]]


## Exercice 2 : Optimisation de la mémoire (`dtype`, `itemsize`)
Imaginons que nous chargeons un gros dataset d'images (pixels de 0 à 255).

**Mission :**
1. Génère un tableau de 1 million d'éléments avec le type par défaut.
2. Calcule son poids en mégaoctets (Mo).
3. Convertis ce tableau dans le type le plus adapté pour des entiers allant de 0 à 255, et compare le nouveau poids.