## Création de tableau

In [ ]:
# lancement de Numpy
import numpy as np

a = np.arange(15).reshape(3, 5)
print(f"Array :\n{a}")
print(f"Shape : {a.shape}, Dimensions : {a.ndim}D, Type : {a.dtype}, Taille : {a.size}")
print(f"Poids d'un élément en mémoire : {a.itemsize} octets" )

In [4]:
# Création à partir de liste
a = np.array([2, 3, 4])
# 2D : Une liste contenant des tuples (séquence de séquences)
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(f"Shape de b : {b.shape}") # (2, 3)

# 3D : Une liste contenant une liste qui contient des listes
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"Shape de c : {c.shape}") # (2, 2, 2)
print(f"Dimensions de c : {c.ndim}D")

Shape de b : (2, 3)
Shape de c : (2, 2, 2)
Dimensions de c : 3D


In [14]:
# 1. Zeros : Idéal pour initialiser les 'biases' en Deep Learning ou servir de compteur
zeros = np.zeros((3, 4))
print(zeros)

# 2. Ones : Utile pour les masques de sélection ou les transformations multiplicatives
ones = np.ones((2, 3, 4), dtype=np.int16)
print(f"\n{ones}")

# 3. Empty : Performance maximale. Attention, contient des données aléatoires (mémoire brute)
# À utiliser uniquement si vous allez écraser toutes les valeurs immédiatement après !
#empty = np.empty((2, 3))
#print(f'\n{empty}')

# 4. Full : Pour une valeur constante spécifique (ex: remplir avec -1 ou pi)
constant = np.full((2, 2), 3.14)
print(f'\n{constant}')


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]

[[3.14 3.14]
 [3.14 3.14]]


In [18]:
# Séquences numériques
# arange : on définit le DEBUT, la FIN (exclue) et le PAS.
print("Arange (quand on connaît le pas) :", np.arange(0, 2, 0.3))

# linspace : on définit le DEBUT, la FIN (incluse) et le NOMBRE D'ÉLÉMENTS.
# Très utilisé pour créer des axes X pour des graphiques.
print("Linspace (nombre d'éléments) :", np.linspace(0, 2, 9))

# Spécification du type complexe (pour le traitement du signal, Fourier, etc.)
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(f"\nTableau complexe :\n{c}")

Arange (quand on connaît le pas) : [0.  0.3 0.6 0.9 1.2 1.5 1.8]
Linspace (nombre d'éléments) : [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

Tableau complexe :
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
