## Scalaire & vecteurs

In [2]:
from pprint import pprint

import numpy as np

patient = np.array([120, 7.3, 28.4])
print(patient.shape)
print(patient[0])
print(patient[1])

(3,)
120.0
7.3


## Matrices

In [3]:
data = np.array([
    [145, 6.8, 28.4],
    [118, 4.9, 22.1],
    [168, 11.3, 31.7]
])

print(data.shape)
print(data[2, 1])
print(data[0])
print(data[:,0])

(3, 3)
11.3
[145.    6.8  28.4]
[145. 118. 168.]


## La transposition : retourner une matrice

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])

A.T
A.T.shape
data = np.array([[145, 6.8], [118, 4.9], [168, 11.3]])
data.T

array([[145. , 118. , 168. ],
       [  6.8,   4.9,  11.3]])

## Connexion direct avec Numpy

In [6]:
# Scalaire
np.float64(12)

# Vecteur
np.array([1, 2, 3]).shape



(3,)

### Broadcasting


In [8]:
means = np.mean(data, axis=0)
print(means)
data_centree = data - means
print(data_centree)

[143.66666667   7.66666667]
[[  1.33333333  -0.86666667]
 [-25.66666667  -2.76666667]
 [ 24.33333333   3.63333333]]


### Créer des matrices utiles

In [15]:
np.zeros((3, 4))
np.ones((2, 5))
np.eye(4)
np.random.randn(100, 5)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Reshape

In [21]:
v = np.arange(12)
print(v)
m = v.reshape(3, 4)
print(m)
M3 = v.reshape(12, 1)
print(M3)
M4 = v.reshape(-1, 4)
print(M4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
