## Création de tableau

In [2]:
# lancement de Numpy
import numpy as np

a = np.arange(15).reshape(3, 5)
print(f"Array :\n{a}")
print(f"Shape : {a.shape}, Dimensions : {a.ndim}D, Type : {a.dtype}, Taille : {a.size}")
print(f"Poids d'un élément en mémoire : {a.itemsize} octets" )

Array :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Shape : (3, 5), Dimensions : 2D, Type : int64, Taille : 15
Poids d'un élément en mémoire : 8 octets


In [4]:
# Création à partir de liste
a = np.array([2, 3, 4])
# 2D : Une liste contenant des tuples (séquence de séquences)
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(f"Shape de b : {b.shape}") # (2, 3)

# 3D : Une liste contenant une liste qui contient des listes
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"Shape de c : {c.shape}") # (2, 2, 2)
print(f"Dimensions de c : {c.ndim}D")

Shape de b : (2, 3)
Shape de c : (2, 2, 2)
Dimensions de c : 3D


In [14]:
# 1. Zeros : Idéal pour initialiser les 'biases' en Deep Learning ou servir de compteur
zeros = np.zeros((3, 4))
print(zeros)

# 2. Ones : Utile pour les masques de sélection ou les transformations multiplicatives
ones = np.ones((2, 3, 4), dtype=np.int16)
print(f"\n{ones}")

# 3. Empty : Performance maximale. Attention, contient des données aléatoires (mémoire brute)
# À utiliser uniquement si vous allez écraser toutes les valeurs immédiatement après !
#empty = np.empty((2, 3))
#print(f'\n{empty}')

# 4. Full : Pour une valeur constante spécifique (ex: remplir avec -1 ou pi)
constant = np.full((2, 2), 3.14)
print(f'\n{constant}')


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]

[[3.14 3.14]
 [3.14 3.14]]


In [18]:
# Séquences numériques
# arange : on définit le DEBUT, la FIN (exclue) et le PAS.
print("Arange (quand on connaît le pas) :", np.arange(0, 2, 0.3))

# linspace : on définit le DEBUT, la FIN (incluse) et le NOMBRE D'ÉLÉMENTS.
# Très utilisé pour créer des axes X pour des graphiques.
print("Linspace (nombre d'éléments) :", np.linspace(0, 2, 9))

# Spécification du type complexe (pour le traitement du signal, Fourier, etc.)
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(f"\nTableau complexe :\n{c}")

Arange (quand on connaît le pas) : [0.  0.3 0.6 0.9 1.2 1.5 1.8]
Linspace (nombre d'éléments) : [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

Tableau complexe :
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


## Opération de base

In [6]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

print("Soustraction", a - b)
print('Puissance :', b**2)
print("Masque booléen (trés utilisé en Pandas) :", a < 35)

# Multiplication matricielle
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print("\nproduit élément par élément (*) :\n", A*B)  # Produit de Hadamard
print("Produit matriciel (@) :\n", A@B, "\nOu\n", A.dot(B))


Soustraction [20 29 38 47]
Puissance : [0 1 4 9]
Masque booléen (trés utilisé en Pandas) : [ True  True False False]

produit élément par élément (*) :
 [[2 0]
 [0 4]]
Produit matriciel (@) :
 [[5 4]
 [3 4]] 
Ou
 [[5 4]
 [3 4]]


## 5. Agrégations et Upcasting

In [8]:
# Opérations unaires (somme, min, max, etc.)
data = np.random.random((2, 3))
print(data)
print("Somme totale :", data.sum())
print("Minimum par colonne (axis=0) :", data.min(axis=0))
print("Minimum par ligne (axis=1) :", data.min(axis=1))
print("Somme cumulée par ligne (axis=1) :\n", data.cumsum(axis=1))

# Upcasting : NumPy transforme automatiquement le type vers le plus précis
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3) # float64 par défaut
c = a + b
print(f"\nType de c (int + float) : {c.dtype}")


[[0.1577763  0.89411255 0.00678019]
 [0.25083952 0.24648279 0.16140942]]
Somme totale : 1.717400760774567
Minimum par colonne (axis=0) : [0.1577763  0.24648279 0.00678019]
Minimum par colonne (axis=1) : [0.00678019 0.16140942]
Somme cumulée par ligne (axis=1) :
 [[0.1577763  1.05188885 1.05866904]
 [0.25083952 0.4973223  0.65873172]]

Type de c (int + float) : float64


## 6. Opérations "In-place" (Mémoire)
# Utile pour modifier un tableau sans en créer un nouveau (gain de performance)

In [10]:
a = np.ones((2, 3), dtype=int)
b = np.random.random((2, 3))

a *= 3  # Équivalent à a = a * 3, mais plus efficace en mémoire
print("In-place multiplication (a *= 3) :\n", a)

# Attention : l'opération += avec un float sur un array int provoquera une erreur
# car NumPy ne veut pas perdre de précision sans que tu le demandes.
b += a  # OK : b est float, a est int -> b reste float
print("Type de b", b.dtype)


In-place multiplication (a *= 3) :
 [[3 3 3]
 [3 3 3]]
Type de b float64


## 7. Indexation Booléenne (Le filtre)

In [16]:
nombres = np.array([10, 25, 40, 55, 70])
masque = nombres > 35
print("Le masque :", masque)
print("Les valeurs filtrées :", nombres[masque])
print("Filtrées les valeur de b", b[b>2])

Le masque : [False False  True  True  True]
Les valeurs filtrées : [40 55 70]
Filtrées les valeur de b [3.99652827 3.86843934 3.16302673 3.22201614 3.44554268 3.20829695]


## Indexation, slicing et itération

In [4]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
print("Array complet:\n", b)

# 1. Accès précis [ligne, colonne]
print("\nDeuxième ligne, troisième colonne (b[2, 3]) :", b[2, 3])

# 2. Slicing : [lignes_début:fin , colonnes_début:fin]
print("\nDeuxième colonne pour toutes les lignes (b[:, 1]) :\n", b[:, 1])
print("Lignes 1 à 3 (exclue), toutes les colonnes (b[1:3, :]) :\n", b[1:3, :])

# 3. Accès par la fin
print("\nDernière ligne (b[-1]) :", b[-1])


Array complet:
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

Deuxième ligne, troisième colonne (b[2, 3]) : 23

Deuxième colonne pour toutes les lignes (b[:, 1]) :
 [ 1 11 21 31 41]
Lignes 1 à 3 (exclue), toutes les colonnes (b[1:3, :]) :
 [[10 11 12 13]
 [20 21 22 23]]

Dernière ligne (b[-1]) : [40 41 42 43]


## 9. Itération
Le slicing crée une vue, si on veux un tableau indépendant utilisons `.copy()`

In [8]:
# Itérer sur un tableau multidimensionnel se fait par rapport au premier axe (les lignes)
print("Itération sur les lignes :")
for row in b[:2]: # On limite aux 2 premières pour l'exemple
    print("Ligne :", row)

print("Itération sur les lignes à partir d'un tableau indépendant de b :")
for row in b[:2].copy(): # On slice d'abord, puis on copie
    print("Ligne :", row)

# Si on veut itérer sur chaque élément individuellement : l'attribut .flat
print("\nItération sur chaque élément (b.flat) :")
for element in b.flat[:5]: # 5 premiers éléments
    print(element, end=" ")


Itération sur les lignes :
Ligne : [0 1 2 3]
Ligne : [10 11 12 13]
Itération sur les lignes à partir d'un tableau indépendant de b :
Ligne : [0 1 2 3]
Ligne : [10 11 12 13]
Ligne : [20 21 22 23]
Ligne : [30 31 32 33]
Ligne : [40 41 42 43]

Itération sur chaque élément (b.flat) :
0 1 2 3 10 

## 10. L'ellipse (...) : l'outil des fainéants intelligents
# Très pratique pour les tableaux à haute dimension (ex: Images RGB (H, W, C))

In [7]:
c = np.arange(24).reshape(2, 3, 4) # 3 dimensions
print("Shape de c :", c.shape)

# Les deux suivants sont équivalents :
print("\nAccès c[1, :, :] :\n", c[1, :, :])
print("Accès avec ellipse c[1, ...] :\n", c[1, ...])

# Utile pour dire "Prendre tout sur les premières dimensions, et seulement l'index 0 de la dernière"
print("\nDernière dimension index 0 (c[..., 0]) :\n", c[..., 0])

Shape de c : (2, 3, 4)

Accès c[1, :, :] :
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Accès avec ellipse c[1, ...] :
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Dernière dimension index 0 (c[..., 0]) :
 [[ 0  4  8]
 [12 16 20]]
