## Les bases
- Dimensions = axes

### Example to use diferents attributs
-**_ndim_** donne le nombre de directions.

-**_shape_** donne la taille qu'à chaque direction.

In [3]:
import numpy as np

a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


### Array creation

In [12]:
a = np.array([2, 3, 4])
a
a.dtype
b = np.array([1.2, 3.5, 5.1])
b.dtype

b = np.array([(1.5, 2, 3), (4, 5, 6)])  # Transformation en séquence bidimensionnel vers tri-dimensionnel
b

# On peut spécifier le dtype.
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

# arange() et linspace()
print(np.arange(0, 2, 0.3))  ## Ici on définit le pas pour le nombre d'occurrences
np.linspace(0, 2, 4)  ## Nous pouvons ici définir le nombre d'occurrences que nous voulons et le pas est défini automatiquement.

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


array([0.        , 0.66666667, 1.33333333, 2.        ])